version: "3"

services:
  wol-over-rest:
    build: .
    container_name: wol-over-rest
    ports:
      - 3000:3000
    restart: on-failure:5
    network_mode: host
    volumes:
      - ./config:/server/config
